FROM ubuntu:24.04@sha256:fdb6c9ceb1293dcb0b7eda5df195b15303b01857d7b10f98489e7691d20aa2a1

ENV TZ=Europe/Berlin

RUN     apt-get update \
    &&  echo "y\ny" | unminimize \
    &&  DEBIAN_FRONTEND=noninteractive apt-get -y install \
            # man Pages
            man \
            man-db \
            # CLI Tools
            vim \
            nano \
            git \
            jq \
            yq \
            gh \
            glab \
            # Helper
            rsync \
            rclone \
            pv \
            # HTTP
            curl \
            wget \
            mitmproxy \
            # Web Browser
            lynx \
            w3m \
            links2 \
            # Clients
            openssh-client \
            mysql-client \
            postgresql-client \
            s3cmd \
            restic \
            # Network and System Tools
            bmon \
            dnsmasq \
            dnsutils \
            iftop \
            iperf \
            iperf3 \
            iproute2 \
            iputils-ping \
            mtr-tiny \
            net-tools \
            netcat-openbsd \
            ncat \
            nmap \
            strace \
            sysstat \
            tcpdump \
            tcptraceroute \
            traceroute \
            telnet

CMD ["/bin/bash"]
