FROM alpine:3.21.0@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45

ARG TARGETPLATFORM

# Already included in BusyBox
#   wget
#   telnet (part of busybox-extras)
#   ip
#   ifconfig
#   ping
#   traceroute
#   nslookup

RUN echo "Run for TARGETPLATFORM: ${TARGETPLATFORM}" && \
    case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64     | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        linux/riscv64   | \
        linux/s390x     ) \
            apk add --no-cache \
                busybox-extras \
                coreutils \
                findutils \
                # CLI Tools
                bash \
                grep \
                vim \
                nano \
                git \
                jq \
                yq \
                helm \
                github-cli \
                glab \
                # HTTP
                curl \
                # Web Browser
                lynx \
                w3m \
                links \
                # Clients
                openssh-client \
                mysql-client \
                s3cmd \
                # Network and System Tools
                bmon \
                iftop \
                iperf \
                mtr \
                nmap \
                strace \
                sysstat \
                tcpdump \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64     | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                postgresql-client \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        # linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64     | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                kubectl \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        # linux/386       | \
        linux/amd64     | \
        # linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64     | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                k9s \
            ;; \
    esac

CMD ["/bin/bash"]
