FROM alpine:3.22.0@sha256:8a1f59ffb675680d47db6337b49d22281a139e9d709335b492be023728e11715

# Already included in BusyBox
#   wget
#   telnet (part of busybox-extras)
#   ip
#   ifconfig
#   ping
#   traceroute
#   nslookup

RUN     apk update \
    &&  for pkg in \
            busybox-extras \
            coreutils \
            findutils \
            # man Pages
            mandoc \
            man-pages \
            mandoc-apropos \
            less \
            # CLI Tools
            bash \
            grep \
            vim \
            nano \
            git \
            jq \
            yq \
            kubectl \
            k9s \
            helm \
            github-cli \
            glab \
            # Helper
            rsync \
            rclone \
            pv \
            # HTTP
            curl \
            mitmproxy \
            # Web Browser
            lynx \
            w3m \
            links \
            # Clients
            openssh-client \
            mysql-client \
            postgresql-client \
            s3cmd \
            restic \
            # Network and System Tools
            bmon \
            dnsmasq \
            iftop \
            iperf \
            mtr \
            nmap \
            strace \
            sysstat \
            tcpdump \
            bind-tools \
            libcap \
        ; do \
            # it's okay for this command to fail
            apk add $pkg || true \
        ; done \
        # Try to install *-doc package for all currently installed packages
    &&  for pkg in $(apk list -I | awk '{print $1}' | sed 's/-[^-]*-[^-]*$//'); do \
            # it's okay for this command to fail
            apk add ${pkg}-doc || true \
        ; done \
    &&  rm -vrf /var/cache/apk/*

CMD ["/bin/bash"]
