FROM alpine:3.20.3@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a

ARG TARGETPLATFORM

# Already included in BusyBox
#   wget
#   telnet (part of busybox-extras)
#   ip
#   ifconfig
#   ping
#   traceroute
#   nslookup

RUN case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        linux/riscv64   | \
        linux/s390x     ) \
            apk add --no-cache \
                busybox-extras \
                # CLI Tools
                bash \
                grep \
                vim \
                nano \
                git \
                jq \
                yq \
                helm \
                # HTTP
                curl \
                # Web Browser
                lynx \
                w3m \
                links \
                # Clients
                openssh-client \
                mysql-client \
                s3cmd \
                # Network and System Tools
                bmon \
                iftop \
                iperf \
                mtr \
                nmap \
                strace \
                sysstat \
                tcpdump \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                postgresql-client \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        linux/386       | \
        linux/amd64     | \
        # linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                kubectl \
            ;; \
    esac && \
    case "${TARGETPLATFORM}" in \
        # linux/386       | \
        linux/amd64     | \
        # linux/arm/v6    | \
        linux/arm/v7    | \
        linux/arm64/v8  | \
        linux/ppc64le   | \
        # linux/riscv64   | \
        linux/s390x     ) \
            apk add \
                k9s \
            ;; \
    esac

CMD ["/bin/bash"]
