FROM ubuntu:22.04

RUN apt-get update && \
    apt-get -y install \
        # CLI Tools
        vim \
        nano \
        # HTTP
        curl \
        wget \
        # Web Browser
        lynx \
        w3m \
        links2 \
        # Clients
        openssh-client \
        mysql-client \
        # Network and System Tools
        bmon \
        dnsutils \
        iftop \
        iperf \
        iputils-ping \
        mtr-tiny \
        net-tools \
        netcat \
        ncat \
        nmap \
        strace \
        sysstat \
        tcpdump \
        tcptraceroute \
        traceroute \
        telnet \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/bin/bash"]
