name: Nightly base image update check

on:
  workflow_dispatch:
  schedule:
    - cron: "13 4 * * *"

jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/ubuntu:latest
          image: dersimn/netutils:ubuntu

      - name: Trigger Rebuild
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
        uses: ./.github/workflows/build-ubuntu.yaml@master

  check-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: dersimn/netutils:alpine

      - name: Trigger Rebuild
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
        uses: ./.github/workflows/build-alpine.yaml@master
