name: Nightly update check Alpine

on:
  workflow_dispatch:
  schedule:
    - cron: "13 4 * * *"

jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: dersimn/netutils:alpine

      - name: Check result
        run: |
          echo "Needs updating: ${{ steps.check.outputs.needs-updating }}"
          if [[ "${{ steps.check.outputs.needs-updating }}" == "false" ]]; then
            echo "No update needed"
            exit 1
          fi

  trigger-build-ubuntu:
    needs: check-ubuntu
    uses: ./.github/workflows/build-alpine.yaml
    secrets: inherit
